chore: Bump Go tools library due to compilation error
The old version would trigger an error when compiled with Go 1.25.0:

# golang.org/x/tools/internal/tokeninternal
../../go/pkg/mod/golang.org/x/tools@v0.19.0/internal/tokeninternal/tokeninternal.go:64:9: invalid array length -delta * delta (constant -256 of type int64)